services:
  nats-server:
    container_name: nats-server
    image: nats:latest

  client-gateway:
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: client-gatewa-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVER_URL=${NATS_SERVER_URL}

  auth-ms:
    depends_on:
      - client-gateway
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
      args:
        - AUTH_MS_DATABASE_URL=${AUTH_MS_DATABASE_URL}
    image: auth-ms-prod
    environment:
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    depends_on:
      - client-gateway
    container_name: products-ms
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=3001
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    depends_on:
      - client-gateway
    container_name: orders-ms
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    image: orders-ms-prod
    environment:
      - PORT=3002
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}

  payments-ms:
    depends_on:
      - client-gateway
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
