services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    depends_on: 
      - nats-server
    container_name: client-gateway
    build: ./client-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVER_URL=${NATS_SERVER_URL}

  auth-db:
    container_name: auth-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./auth-ms/postgres:/var/lib/postgresql/data
    ports:
      - "5451:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth

  auth-ms:
    depends_on:
      - client-gateway
      - auth-db
    container_name: auth-ms
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    depends_on:
      - client-gateway
    container_name: products-ms
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3001
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - DATABASE_URL=file:./dev.db

  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders

  orders-ms:
    depends_on:
      - orders-db
      - client-gateway
    container_name: orders-ms
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: yarn run start:dev
    environment:
      - PORT=3002
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}

  payments-ms:
    depends_on:
      - client-gateway
    container_name: payments-ms
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"      
    command: yarn run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVER_URL=${NATS_SERVER_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
